### ISSUE TITLE
Error with crm 8.0 and dependencyxml attribute

### ISSUE THREAD

**Issue by gromhm** [MscrmTools/MsCrmTools.WebResourcesManager#105]
With last update i got a new exception "An exception occured while retrieving webresources: 'WebResource' entity doesn't contain attribute with Name = 'dependencyxml'."

**Comment by MscrmTools** [comment]
Well the issue existed since many version, not only the last one. But I thought I had tackle down this one in latest release...

[this commit](https://github.com/MscrmTools/MsCrmTools.WebResourcesManager/commit/edd585b1abfdc0add00708bbdbf39e78f86dd26e) removes the dependencyxml attribute if org is < 8.2

**Comment by MathieuLEPOUTRE** [comment]
It seems there was a typo in the last commit, it does not work for version 8.1
if (detail.OrganizationMajorVersion < 8 || detail.OrganizationMajorVersion == 8 && detail.OrganizationMajorVersion < 2)
should be
if (detail.OrganizationMajorVersion < 8 || detail.OrganizationMajorVersion == 8 && detail.OrganizationMinorVersion < 2)
?

**Comment by MscrmTools** [comment]
Crap! Typo mistake as you said. 
I will release a new version ASAP
