### ISSUE TITLE
Question: Rename javascript file. What happens with existing events

### ISSUE THREAD

**Issue by daggen** [MscrmTools/MsCrmTools.WebResourcesManager#80]
Hi, 

What will happen to all form events already existing and pointing to a javascript file if you rename it?

**Comment by BetimBeja** [comment]
Hello @daggen 
Since renaming is not possible for webresources the tool actually fakes the rename by deleting the existing webresource and uploading a new one with the new name, and since you cannot delete a webresource if it has dependencies the rename fails in that case. See demonstration below:
![Issue 80](https://user-images.githubusercontent.com/11160171/63433412-722d9480-c423-11e9-863c-d26283097f47.gif)

Best regards,
Betim Beja.
